language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t dockerivadev/multi -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true dockerivadev/multi npm test
 #- docker run ivanovadev/multi npm run test -- --coverage
  

after_success:
 - docker build -t dockerivadev/multi-client ./client
 - docker build -t dockerivadev/multi-nginx ./nginx
 - docker build -t dockerivadev/multi-server ./server
 - docker build -t dockerivadev/multi-worker ./worker

 # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
 
 - docker push dockerivadev/multi-client
 - docker push dockerivadev/multi-nginx
 - docker push dockerivadev/multi-server
 - docker push dockerivadev/multi-worker

 


